"""Company Table

Revision ID: c1a0fca2d4e6
Revises: 
Create Date: 2019-10-18 00:44:29.026190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a0fca2d4e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('company_vision', sa.String(length=255), nullable=True),
    sa.Column('date_founded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=True)
    op.create_table('need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplies_needed', sa.String(length=255), nullable=True),
    sa.Column('volunteers_needed', sa.String(length=255), nullable=True),
    sa.Column('money_needed', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('need')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
